/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CCSADJ0nIY4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function SpotifyLogin() {
    return (
        <div className="flex items-center justify-center min-h-screen bg-black text-white">
            <div className="flex w-full max-w-4xl gap-8 p-4 md:p-8">
                <div className="flex flex-col items-center justify-center flex-1">
                    <Button
                        className="mt-8 bg-[#1DB954] text-white hover:bg-[#1ED760] px-12 py-2 rounded-full font-medium items-center">
                        <img src="../../../public/next.svg" alt="spotifylogo" className="w-6 h-6 mr-2"/>
                        Login with Spotify
                    </Button>
                </div>
            </div>
        </div>
    )
}